# Generated by Django 4.2.5 on 2023-10-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='제목 적어야 함', max_length=30),
        ),
    ]
