# Generated by Django 4.2.3 on 2023-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_remove_schedule_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
